"""
api/main.py — Phase 6 — FastAPI Server
Exposes the RAG pipeline as a REST API on port 8001.

Endpoints:
    POST /api/suggestions  — main suggestion endpoint
    GET  /health           — liveness probe
    GET  /docs             — interactive Swagger UI (auto-generated by FastAPI)

Run with:
    cd rag-service
    uvicorn api.main:app --reload --port 8001
"""
import os

from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, field_validator

load_dotenv()

# ─────────────────────────────────────────────────────────────────────────────
# App init
# ─────────────────────────────────────────────────────────────────────────────

app = FastAPI(
    title="Career.ai RAG Suggestion Engine",
    description="Retrieval-Augmented Generation engine that compares a candidate resume "
                "against 480+ winning benchmark resumes and returns structured improvement suggestions.",
    version="1.0.0",
    docs_url="/docs",
    redoc_url="/redoc",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:3000",
        "http://127.0.0.1:3000",
        "https://career.ai",
        "https://*.vercel.app",
    ],
    allow_credentials=True,
    allow_methods=["POST", "GET"],
    allow_headers=["*"],
)

# ─────────────────────────────────────────────────────────────────────────────
# Pipeline (lazy-imported so startup is fast even without ChromaDB)
# ─────────────────────────────────────────────────────────────────────────────

def _get_pipeline():
    from engine.pipeline import run_rag_pipeline
    return run_rag_pipeline


# ─────────────────────────────────────────────────────────────────────────────
# Request / Response Schemas
# ─────────────────────────────────────────────────────────────────────────────

class SuggestionRequest(BaseModel):
    resume_text: str
    job_description: str
    job_role: str | None = None

    @field_validator("resume_text")
    @classmethod
    def resume_not_empty(cls, v: str) -> str:
        if len(v.strip()) < 100:
            raise ValueError("resume_text must be at least 100 characters")
        return v

    @field_validator("job_description")
    @classmethod
    def jd_not_empty(cls, v: str) -> str:
        if len(v.strip()) < 50:
            raise ValueError("job_description must be at least 50 characters")
        return v


# ─────────────────────────────────────────────────────────────────────────────
# Endpoints
# ─────────────────────────────────────────────────────────────────────────────

@app.get("/health")
async def health():
    """Liveness probe."""
    return {
        "status": "ok",
        "service": "career.ai RAG Suggestion Engine",
        "version": "1.0.0",
        "embedding_model": "all-MiniLM-L6-v2",
        "llm": "claude-sonnet-4-20250514",
        "vector_db": "chromadb (cosine)",
    }


@app.get("/")
async def root():
    return {
        "message": "Career.ai RAG Suggestion Engine running 🚀",
        "docs": "/docs",
        "health": "/health",
    }


@app.post("/api/suggestions")
async def get_suggestions(req: SuggestionRequest):
    """
    Analyse a candidate resume against benchmark resumes and return
    structured improvement suggestions.

    Body:
        resume_text      — the candidate's resume as plain text (required, min 100 chars)
        job_description  — target job description (required, min 50 chars)
        job_role         — e.g. 'Software Engineer' (optional, improves retrieval accuracy)

    Returns:
        score_current, score_projected, top_insight,
        missing_keywords, weak_bullets, structural_issues,
        strengths, benchmark_insight, benchmark_keywords,
        benchmarks_used, avg_similarity
    """
    try:
        run_pipeline = _get_pipeline()
        result = run_pipeline(
            user_resume=req.resume_text,
            job_description=req.job_description,
            job_role=req.job_role,
        )
    except FileNotFoundError as e:
        raise HTTPException(
            status_code=503,
            detail=f"ChromaDB not initialised. Run scripts/ingest.py first. ({e})",
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Pipeline error: {e}")

    if "error" in result:
        raise HTTPException(status_code=502, detail=result)

    return result


# ─────────────────────────────────────────────────────────────────────────────
# Dev runner
# ─────────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import uvicorn

    host = os.getenv("HOST", "0.0.0.0")
    port = int(os.getenv("PORT", "8001"))
    uvicorn.run("api.main:app", host=host, port=port, reload=True)
